config/routes.rb
Rails.application.routes.draw do
  get '/game', to: 'grids#game'

  get '/score', to: 'grids#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grids_controller.rb
require 'open-uri'

class GridsController < ApplicationController
  def game
    @grid = generate_grid(rand(3..1000))
    @start_time = Time.now.to_i
  end

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a.sample }
  end

  def included?(guess, grid)
    guess.chars.all? do |letter|
      guess.count(letter) <= grid.count(letter)
    end
    byebug
  end

  def compute_score(attempt, time_taken)
    time_taken > 60.0 ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    new_grid = grid.split("")
    result = { time: end_time - start_time.to_i }

    score_and_message = score_and_message(attempt, new_grid, result[:time])
    result[:score] = score_and_message.first
    result[:message] = score_and_message.last

    result
  end

  def score_and_message(attempt, grid, time)
    if included?(attempt.upcase, grid)
      if english_word?(attempt)
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def english_word?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    return json['found']
  end


  def score
    end_time = Time.now.to_i
    @score = run_game(params[:attempt], params[:grid], params[:start_time], end_time)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/views/grids/game.html.erb
<h1>Grids#game</h1>
<p> <%= @grid  %></p>
<div>
  <form action="/score" method="GET">
    <input type="text" name='attempt'>
    <input type="hidden" name='start_time' value=<%= @start_time %> >
    <input type="hidden" name='grid' value=<%= @grid.join %> >

    <input type="submit">
  </form>
</div>

app/views/grids/score.html.erb
<h1>Grids#score</h1>
<p><%= @score  %></p>

<%= link_to "nouvel essai", game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>